version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-swim
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: liga_natacion
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
