# pylint: disable=no-member
"""Tablas principales

Revision ID: 219a77aecf82
Revises: f429691d2142
Create Date: 2025-05-25 13:31:27.926982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219a77aecf82'
down_revision: Union[str, None] = 'f429691d2142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_fundacion', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubes_id'), 'clubes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contra', sa.String(), nullable=False),
    sa.Column('fecha_asig', sa.Date(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'entrenador', 'club', name='rolusuarioenum'), nullable=False),
    sa.Column('contacto', sa.String(length=20), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contacto'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('entrenadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('contacto', sa.String(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('disciplinas', sa.JSON(), nullable=False),
    sa.Column('categorias', sa.JSON(), nullable=False),
    sa.Column('experiencia', sa.String(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.Column('id_club', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_club'], ['clubes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_entrenadores_id'), 'entrenadores', ['id'], unique=False)
    op.create_table('nadadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('categorias', sa.String(), nullable=True),
    sa.Column('disciplinas', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('experiencia', sa.String(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.Column('id_entrenador', sa.Integer(), nullable=True),
    sa.Column('id_club', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_club'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nadadores_id'), 'nadadores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nadadores_id'), table_name='nadadores')
    op.drop_table('nadadores')
    op.drop_index(op.f('ix_entrenadores_id'), table_name='entrenadores')
    op.drop_table('entrenadores')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clubes_id'), table_name='clubes')
    op.drop_table('clubes')
    # ### end Alembic commands ###
