"""agregar club_id a entrenador

Revision ID: fa554ecf832f
Revises: 3baad27a3911
Create Date: 2025-05-10 17:04:37.246581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa554ecf832f'
down_revision: Union[str, None] = '3baad27a3911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entrenadores', 'clubes', ['club_id'], ['id'])
    op.drop_column('entrenadores', 'club_actual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('club_actual', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entrenadores', type_='foreignkey')
    op.drop_column('entrenadores', 'club_id')
    # ### end Alembic commands ###
